name: CI Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Sync dependencies for DEV
        run: uv sync --dev

      - name: Run mypy
        run: uv run mypy .

      - name: Run ruff
        run: uv run ruff check

      - name: Run pytest
        run: uv run pytest